apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace-config.yaml
  - 02-postgres.yaml
  - 03-redis.yaml
  - 04-backend.yaml
  - 05-frontends.yaml
  - 07-intelligence.yaml

secretGenerator:
  - name: lumora-secret
    namespace: lumora
    envs:
      - .env
